#!/usr/bin/env python3
"""Build staged variants of the rejected solenoid PCB patch for parser isolation.

Usage:
  debug_rev_a_solenoid_pcb_serialization.py ORIGINAL FULL OUTDIR

The FULL board is the in-workspace result of patch_rev_a_solenoid_pcb.py.
Nothing generated by this helper belongs in the repository; the workflow runs
KiCad against the variants in /tmp and commits only a text report.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path


def extract_block(text: str, start: int) -> tuple[str, int]:
    depth = 0
    in_string = False
    escaped = False
    for i in range(start, len(text)):
        c = text[i]
        if in_string:
            if escaped:
                escaped = False
            elif c == "\\":
                escaped = True
            elif c == '"':
                in_string = False
            continue
        if c == '"':
            in_string = True
        elif c == '(':
            depth += 1
        elif c == ')':
            depth -= 1
            if depth == 0:
                return text[start:i + 1], i + 1
    raise RuntimeError(f"unbalanced block starting at byte {start}")


def blocks(text: str, token: str):
    p = 0
    while True:
        p = text.find(token, p)
        if p < 0:
            return
        block, end = extract_block(text, p)
        yield p, end, block
        p = end


def fp_ref(block: str) -> str:
    m = re.search(r'\(fp_text reference "([^"]+)"', block)
    return m.group(1) if m else ''


def tstamp(block: str) -> str:
    m = re.search(r'\(tstamp ([0-9a-f-]+)\)', block)
    return m.group(1) if m else ''


def remove_new_routes(full: str, original: str) -> str:
    old_ids = set()
    for token in ('(segment ', '(via '):
        for _, _, b in blocks(original, token):
            ts = tstamp(b)
            if ts:
                old_ids.add(ts)

    removals = []
    for token in ('(segment ', '(via '):
        for s, e, b in blocks(full, token):
            ts = tstamp(b)
            if ts and ts not in old_ids:
                removals.append((s, e))
    out = full
    for s, e in sorted(removals, reverse=True):
        out = out[:s] + out[e:]
    return out


def remove_new_footprints(text: str) -> str:
    refs = {'Q805', 'Q806', 'R820', 'R821', 'R822', 'TP703'}
    removals = []
    for s, e, b in blocks(text, '(footprint '):
        if fp_ref(b) in refs:
            removals.append((s, e))
    out = text
    for s, e in sorted(removals, reverse=True):
        out = out[:s] + out[e:]
    return out


def insert_net_defs(original: str) -> str:
    out = original.replace('/ESP32/ESP21', 'SOLENOID_PWR_EN')
    defs = (
        '  (net 153 "SOLENOID_12V_SW")\n'
        '  (net 154 "Net-(Q805-G)")\n'
        '  (net 155 "Net-(Q806-G)")\n'
    )
    p = out.find('  (footprint ')
    if p < 0:
        raise RuntimeError('first footprint anchor missing')
    return out[:p] + defs + out[p:]


def balance_summary(text: str) -> str:
    depth = 0
    in_string = False
    escaped = False
    min_depth = 0
    for c in text:
        if in_string:
            if escaped:
                escaped = False
            elif c == "\\":
                escaped = True
            elif c == '"':
                in_string = False
            continue
        if c == '"':
            in_string = True
        elif c == '(':
            depth += 1
        elif c == ')':
            depth -= 1
            min_depth = min(min_depth, depth)
    return f'depth={depth} min_depth={min_depth} in_string={in_string}'


def root_tokens(text: str, limit: int = 80) -> list[str]:
    """Return first root-child token names for ordering inspection."""
    result = []
    depth = 0
    in_string = False
    escaped = False
    i = 0
    while i < len(text) and len(result) < limit:
        c = text[i]
        if in_string:
            if escaped:
                escaped = False
            elif c == "\\":
                escaped = True
            elif c == '"':
                in_string = False
            i += 1
            continue
        if c == '"':
            in_string = True
            i += 1
            continue
        if c == '(':
            depth += 1
            if depth == 2:
                m = re.match(r'\(([A-Za-z0-9_.*+-]+)', text[i:])
                if m:
                    result.append(m.group(1))
        elif c == ')':
            depth -= 1
        i += 1
    return result


def main() -> None:
    if len(sys.argv) != 4:
        raise SystemExit('usage: script ORIGINAL FULL OUTDIR')
    orig_path, full_path, outdir = map(Path, sys.argv[1:])
    outdir.mkdir(parents=True, exist_ok=True)
    original = orig_path.read_text(errors='strict')
    full = full_path.read_text(errors='strict')

    no_routes = remove_new_routes(full, original)
    migration_only = remove_new_footprints(no_routes)
    defs_only = insert_net_defs(original)

    variants = {
        '00_original.kicad_pcb': original,
        '10_netdefs_rename.kicad_pcb': defs_only,
        '20_migration_only.kicad_pcb': migration_only,
        '30_with_footprints.kicad_pcb': no_routes,
        '40_full.kicad_pcb': full,
    }
    meta = []
    for name, text in variants.items():
        (outdir / name).write_text(text)
        meta.append(f'{name}: bytes={len(text)} {balance_summary(text)}')
    (outdir / 'meta.txt').write_text('\n'.join(meta) + '\n\nroot tokens full:\n' + '\n'.join(root_tokens(full)) + '\n')
    print((outdir / 'meta.txt').read_text())


if __name__ == '__main__':
    main()
